"use client";
import { useState, useEffect } from "react";
import { X, ChevronRight, ChevronLeft } from "lucide-react";

const STEPS = [
  {
    emoji: "👋",
    color: "#00ff88",
    title: "Welcome to QuantSignal",
    subtitle: "Here's how to use it in 5 steps",
    body: "QuantSignal scans 86 assets every time you load it and tells you which ones have a high-probability trading opportunity right now. This quick walkthrough shows you exactly how to read and act on what you see.",
  },
  {
    emoji: "🎯",
    color: "#00aaff",
    title: "Step 1 — Pick an asset",
    subtitle: "Start with what you already trade",
    body: "Use the left panel to browse assets. Filter by CRYPTO, STOCK, FOREX, or any category. Each card shows the direction (BUY/SELL/HOLD) and a confidence percentage. Start with assets you're familiar with — BTC, NVDA, AAPL, or EUR/USD.",
  },
  {
    emoji: "📊",
    color: "#aa44ff",
    title: "Step 2 — Read the signal",
    subtitle: "Direction + confidence + confluence",
    body: "Click any asset to open the full detail view. You'll see three things: the ML direction (BUY/SELL/HOLD), the confidence percentage (higher = stronger signal), and the 9-factor confluence score (e.g. 7/9 BULLISH means 7 out of 9 technical indicators agree).",
  },
  {
    emoji: "💰",
    color: "#ffd700",
    title: "Step 3 — Check your levels",
    subtitle: "Entry, Take Profit, Stop Loss",
    body: "Every signal comes with three price levels. Entry is the current price. Take Profit is your target — where to exit with a gain. Stop Loss is your protection — where to exit to cut losses. These are calculated using ATR (market volatility), not guesswork.",
  },
  {
    emoji: "⚖️",
    color: "#ff6644",
    title: "Step 4 — Size your position",
    subtitle: "Use the Kelly % as a guide",
    body: "The Kelly Size tells you what percentage of your available capital to risk on this trade. For example, Kelly 5% means if you have ₹1,00,000 to trade, risk ₹5,000 on this position. This is a mathematical guide — always use your own judgment.",
  },
  {
    emoji: "⚠️",
    color: "#ff4466",
    title: "One last thing",
    subtitle: "This is education, not advice",
    body: "QuantSignal is an educational tool. These signals are generated by ML models and do not constitute financial advice. Markets can move against any signal. Always use stop losses, never risk more than you can afford to lose, and do your own research.",
    cta: "I understand — let's trade",
  },
];

export default function TutorialModal() {
  const [visible, setVisible] = useState(false);
  const [step, setStep] = useState(0);

  useEffect(() => {
    const handleOpen = () => { setStep(0); setVisible(true); };
    window.addEventListener("open-tutorial", handleOpen);
    
    const seen = localStorage.getItem("qs_tutorial_seen");
    if (!seen) setVisible(true);
    
    return () => window.removeEventListener("open-tutorial", handleOpen);
  }, []);

  const dismiss = () => {
    localStorage.setItem("qs_tutorial_seen", "1");
    setVisible(false);
  };

  if (!visible) return null;

  const current = STEPS[step];
  const isLast = step === STEPS.length - 1;

  return (
    <div style={{
      position: "fixed", inset: 0, zIndex: 1000,
      background: "rgba(0,0,0,0.8)", backdropFilter: "blur(8px)",
      display: "flex", alignItems: "center", justifyContent: "center",
      padding: 24, fontFamily: "'IBM Plex Mono', monospace",
    }}>
      <div style={{
        background: "#0f0f17", border: "1px solid rgba(255,255,255,0.1)",
        borderRadius: 16, width: "100%", maxWidth: 500,
        padding: 40, position: "relative",
      }}>
        {/* Close */}
        <button onClick={dismiss} style={{
          position: "absolute", top: 16, right: 16,
          background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.08)",
          borderRadius: 8, padding: 8, cursor: "pointer", color: "rgba(255,255,255,0.4)",
          display: "flex", alignItems: "center",
        }}><X size={16} /></button>

        {/* Progress bar */}
        <div style={{ display: "flex", gap: 6, marginBottom: 32 }}>
          {STEPS.map((_, i) => (
            <div key={i} onClick={() => setStep(i)} style={{
              height: 3, flex: i <= step ? 2 : 1,
              background: i <= step ? current.color : "rgba(255,255,255,0.1)",
              borderRadius: 2, cursor: "pointer", transition: "all 0.3s",
            }} />
          ))}
        </div>

        {/* Emoji */}
        <div style={{ fontSize: 48, marginBottom: 20 }}>{current.emoji}</div>

        {/* Step label */}
        <div style={{ fontSize: 9, color: "rgba(255,255,255,0.3)", letterSpacing: "0.15em", marginBottom: 8 }}>
          {step === 0 ? "WELCOME" : `STEP ${step} OF ${STEPS.length - 1}`}
        </div>

        {/* Title */}
        <div style={{ fontSize: 20, fontWeight: 700, color: "#e2e8f0", marginBottom: 6, lineHeight: 1.3 }}>
          {current.title}
        </div>
        <div style={{ fontSize: 11, color: current.color, marginBottom: 20, letterSpacing: "0.05em" }}>
          {current.subtitle}
        </div>
        <div style={{ fontSize: 13, color: "rgba(255,255,255,0.6)", lineHeight: 1.9, marginBottom: 36 }}>
          {current.body}
        </div>

        {/* Navigation */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <button onClick={() => step > 0 && setStep(step - 1)} style={{
            background: "transparent", border: "1px solid rgba(255,255,255,0.1)",
            borderRadius: 8, padding: "10px 20px",
            color: step === 0 ? "rgba(255,255,255,0.15)" : "rgba(255,255,255,0.5)",
            cursor: step === 0 ? "default" : "pointer",
            fontSize: 12, fontFamily: "inherit",
            display: "flex", alignItems: "center", gap: 6,
          }}>
            <ChevronLeft size={14} /> Back
          </button>

          <button onClick={isLast ? dismiss : () => setStep(step + 1)} style={{
            background: isLast ? current.color : "rgba(255,255,255,0.08)",
            border: `1px solid ${isLast ? current.color : "rgba(255,255,255,0.12)"}`,
            borderRadius: 8, padding: "10px 24px",
            color: isLast ? "#000" : "rgba(255,255,255,0.8)",
            cursor: "pointer", fontSize: 12, fontFamily: "inherit", fontWeight: 600,
            display: "flex", alignItems: "center", gap: 6,
          }}>
            {isLast ? (current.cta || "Get Started →") : <>Next <ChevronRight size={14} /></>}
          </button>
        </div>

        {!isLast && (
          <div style={{ textAlign: "center", marginTop: 16 }}>
            <button onClick={dismiss} style={{
              background: "none", border: "none",
              color: "rgba(255,255,255,0.2)", fontSize: 11,
              cursor: "pointer", fontFamily: "inherit",
            }}>Skip tutorial</button>
          </div>
        )}
      </div>
    </div>
  );
}
